#! /bin/sh
# /etc/init.d/lmidi

# If you want a command to always run, put it here

# Carry out specific functions when asked to by the system
case "$1" in
  start)
    echo "Starting lmidi"
    # run application you want to start
    su pi <<'EOC'
    cd /home/pi/l-midi/processing
    COUNTER=0
    while [ 1 ]; do
        echo Run $COUNTER
        DISPLAY=:0 processing-java --sketch=lmidi --present
    let COUNTER=COUNTER+1
    done
EOC
    ;;
  stop)
    echo "Stopping lmidi"
    # kill application you want to stop
    killall processing-java
    ;;
  *)
    echo "Usage: /etc/init.d/lmidi {start|stop}"
    exit 1
    ;;
esac

exit 0
