#! /bin/sh
# /etc/init.d/lmidi

### BEGIN INIT INFO
# Provides:          lmidi
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start lmidi application on boot
# Description:       This launches the lmidi application which requires sends serial data to a connected Arduino.
### END INIT INFO

# If you want a command to always run, put it here

# Carry out specific functions when asked to by the system
case "$1" in
  start)
    echo "Starting lmidi"
    # run application you want to start
		/home/pi/l-midi/processing/scripts/start.sh
    ;;
  stop)
    echo "Stopping lmidi"
    # kill application you want to stop
    killall processing-java
    ;;
  *)
    echo "Usage: /etc/init.d/lmidi {start|stop}"
    exit 1
    ;;
esac

exit 0
